### PR TITLE
Add ansible mixin to mixin list

### LINKED ISSUE #1060: Ansible mixin
**Is your feature request related to a problem? Please describe.**
It would be nice to have an Ansible mixin. If I get time, I'll try it myself.

Just creating this issue to track that more transparently if others are interested.

**Describe the solution you'd like**
We have an Ansible porter mixin.

**Describe alternatives you've considered**
Using the exec mixin :point_right: https://git.autonomic.zone/decentral1se/gitea-cnab

**Additional context**
Guess https://github.com/deislabs/porter-skeletor is the place to start

### PR DESCRIPTION
**Pull request by LvffY**
Closes https://github.com/getporter/porter/issues/1060.

The code for the ansible mixin is at [LvffY/ansible-mixin](https://github.com/LvffY/ansible-mixin). Any review and or suggestions are welcome :)

### CODE REVIEW

**Comment by carolynvs** [comment]
This looks great! 🎉 I don't have time today to review the mixin but will make time tomorrow.

Would you be interested suggestions for the mixin syntax itself? I think we can simplify the yaml for the end user (for example, not having to explicitly have adhoc while still allowing arbitrary commands. If that would be welcome feedback, let me know, otherwise I'll just do a check for any potential problems with the mixin.

**Comment by LvffY** [comment]
@carolynvs It would be great to have any feedback and/or suggestions 👌

I already know an issue : in my [action_test](https://github.com/LvffY/ansible-mixin/blob/main/pkg/ansible/action_test.go),  I can't access to he **Outputs** array. If you have any leads about why, I'll take it.

***DISCLAIMER:*** *These are my very first lines in Go, so I probably miss something obvious, dont be surprised* 😄

**Comment by LvffY** [comment]
@carolynvs Did you have the time to look at at this ? 

If you don't, no problem for me, don't worry :)

**Review by carolynvs — APPROVED** [review]
Install worked, thanks for sharing your mixin! 👍

**Comment by carolynvs** [comment]
@LvffY Sorry I got a bit swamped for a few days! 

I noticed that `ansible version` wasn't printing out the version of your mixin, which can cause problems when building bundles. I've submitted a PR to your repo to fix that: https://github.com/getporter/packages/pull/22/files

My only suggestion was that you can make adhoc your default command, instead of returning an error in default. 

https://github.com/LvffY/ansible-mixin/blob/517a9b17aa0786d9a14d3083841758d4a8e51ddf/pkg/ansible/action.go#L101-L109

This would let you have special commands, and then if they aren't using a special command, run any artibrary command without having to explicitly say "adhoc". That would be a bit more consistent with the other mixins. Totally up to you!

```yaml
install:
  - ansible:
      description: "Run our ansible adhoc command with all fields"
      arguments:
        - "host_pattern*"
      flags:
        inventory: "/etc/ansible/hosts"
        module-name: "debug"
        args: "var=variable_name"
      dir: "/working/dir"
      suppress-output: true
      suffix-arguments:
        - "foo"
        - "bar"
```

**Pull request merged**
